app_second/urls.py
from django.urls import path, re_path
from . import views

app_name = 'app_name_todo_list'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.home, name=''),
    path('home/', views.home, name='home'),

    path('todo/create/', views.create, name='create'),
    path('todo/<int:todo_id>/', views.read, name='read'),
    path('todo/list/', views.read_list, name='read_list'),
    path('todo/<int:todo_id>/update/', views.update, name='update'),
    re_path(r'^todo/(?P<todo_id>\d+)/delete/$', views.delete, name='delete'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('todo_list/', include('app_todo_list.urls')),
]

urlpatterns += [re_path(r'^.*$', lambda request: redirect('', permanent=False), name='redirect')]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_second/models.py
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.db import models

# Create your models here.
from django.utils import timezone


class Todo(models.Model):
    """
    Модель, которая содержит токен пользователя django
    """

    title = models.CharField(
        db_column='title_db_column',
        db_index=True,
        db_tablespace='title_db_tablespace',
        error_messages=False,
        primary_key=False,
        validators=[MinLengthValidator(0), MaxLengthValidator(300), ],
        unique=False,
        editable=True,
        blank=True,
        null=True,
        default='',
        verbose_name='Заголовок',
        help_text='<small class="text-muted">CharField [0, 300]</small><hr><br>',

        max_length=300,
    )
    description = models.TextField(
        db_column='description_db_column',
        db_index=True,
        db_tablespace='description_db_tablespace',
        error_messages=False,
        primary_key=False,
        validators=[MinLengthValidator(0), MaxLengthValidator(3000), ],
        unique=False,
        editable=True,
        blank=True,
        null=True,
        default="",
        verbose_name='Описание',
        help_text='<small class="text-muted">TextField [0, 3000]</small><hr><br>',

        max_length=3000,
    )
    is_completed = models.BooleanField(
        db_column='is_completed_db_column',
        db_index=True,
        db_tablespace='is_completed_db_tablespace',
        error_messages=False,
        primary_key=False,
        unique=False,
        editable=True,
        blank=True,
        null=False,
        default=False,
        verbose_name='Статус выполнения',
        help_text='<small class="text-muted">BooleanField</small><hr><br>',
    )
    created = models.DateTimeField(
        db_column='created_db_column',
        db_index=True,
        db_tablespace='created_db_tablespace',
        error_messages=False,
        primary_key=False,
        unique=False,
        editable=True,
        blank=True,
        null=True,
        default=timezone.now,
        verbose_name='Дата и время создания',
        help_text='<small class="text-muted">DateTimeField</small><hr><br>',

        auto_now=False,
        auto_now_add=False,
    )
    updated = models.DateTimeField(
        db_column='updated_db_column',
        db_index=True,
        db_tablespace='updated_db_tablespace',
        error_messages=False,
        primary_key=False,
        unique=False,
        editable=True,
        blank=True,
        null=True,
        default=timezone.now,
        verbose_name='Дата и время обновления',
        help_text='<small class="text-muted">DateTimeField</small><hr><br>',

        auto_now=False,
        auto_now_add=False,
    )

    class Meta:
        app_label = 'app_todo_list'
        ordering = ('-updated',)
        verbose_name = 'Todo'
        verbose_name_plural = 'Todos'
        db_table = 'todo_todo_list_model_table'

    def __str__(self):
        if self.is_completed:
            completed = "Активно"
        else:
            completed = "Неактивно"
        return f"{self.title} | {self.description[0:30]}... | {completed} | {self.updated}"

app_second/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.utils import timezone

from . import models


# Create your views here.


def index(request):
    return HttpResponse("<h1>This is a Index Page</h1>")


def home(request):
    context = {

    }
    return render(request, 'app_todo_list/pages/home.html', context)


def create(request):
    if request.method == 'POST':
        title = request.POST.get("title", "")
        description = request.POST.get("description", "")
        models.Todo.objects.create(
            title=title,
            description=description,
            is_completed=False,
        )
        return redirect(reverse('app_name_todo_list:read_list', args=()))
    context = {
    }
    return render(request, 'app_todo_list/pages/todo_create.html', context)


def read(request, todo_id=None):
    todo = models.Todo.objects.get(id=todo_id)
    context = {
        "todo": todo
    }
    return render(request, 'app_todo_list/pages/todo_detail.html', context)


def read_list(request):
    is_detail_view = request.GET.get("is_detail_view", True)
    if is_detail_view == "False":
        is_detail_view = False
    elif is_detail_view == "True":
        is_detail_view = True
    todo_list = models.Todo.objects.all()

    def paginate(objects, num_page):
        paginator = Paginator(objects, num_page)
        pages = request.GET.get('page')
        try:
            page = paginator.page(pages)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        return page

    page = paginate(objects=todo_list, num_page=4)

    context = {
        # "todo_list": todo_list,
        "page": page,
        "is_detail_view": is_detail_view
    }
    return render(request, 'app_todo_list/pages/todo_list.html', context)


def update(request, todo_id=None):
    if request.method == 'POST':
        todo = models.Todo.objects.get(id=todo_id)
        is_completed = request.POST.get("is_completed", "")
        title = request.POST.get("title", "")
        description = request.POST.get("description", "")
        if is_completed:
            if is_completed == "False":
                todo.is_completed = False
            elif is_completed == "True":
                todo.is_completed = True
        if title and title != todo.title:
            todo.title = title
        if description and description != todo.description:
            todo.description = description
        todo.updated = timezone.now()
        todo.save()
        return redirect(reverse('app_name_todo_list:read_list', args=()))
    todo = models.Todo.objects.get(id=todo_id)
    context = {
        "todo": todo
    }
    return render(request, 'app_todo_list/pages/todo_change.html', context)


def delete(request, todo_id=None):
    models.Todo.objects.get(id=todo_id).delete()
    return redirect(reverse('app_name_todo_list:read_list', args=()))

templates/app_todo_list/components/aborted.html
<hr/>
<div class="container">
    <div class="container-fluid">
        <p class="lead text-center text-danger">Not have any data!</p>
    </div>
</div>
<hr/>

templates/app_todo_list/components/footer.html
<footer class="container-fluid mt-auto footer page-footer custom-background-transparent-middle-hard">
    <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
        <li class="m-1 p-1">
            <div class="navbar">
                <a class="btn btn-sm btn-outline-secondary" href="#">to TOP</a>
            </div>
        </li>
        <li class="m-1 p-1">
            <div class="navbar dropup">
                <a class="dropdown-toggle btn btn-sm  btn-outline-danger" role="button" data-bs-toggle="dropdown">Help!</a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                        <strong class="dropdown-header">Mobile phone</strong>
                            <a class="dropdown-item disabled" href="#">+7 747 261 03 59</a>
                        <hr class="dropdown-divider">
                    </li>
                    <li>
                        <strong class="dropdown-header">Email (google)</strong>
                        <a class="dropdown-item disabled" href="#">bogdandrienko@gmail.com</a>
                    </li>
                </ul>
            </div>
        </li>
    </ul>
</footer>

templates/app_todo_list/components/navbar.html
{% load app_todo_list_extras %}

<nav class="container-fluid navbar navbar-expand-lg navbar-light custom-background-transparent-middle-hard">
    <a class="navbar-brand" href="{% url 'app_name_todo_list:' %}">MAIN</a>
    <a class="navbar-brand" href="{% url 'app_name_todo_list:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% access_tag 'module_modules' as module_modules %}
    {% if module_modules %}
        <ul class="navbar-nav navbar-collapse collapse" id="navbarSupportedContent">
            {% access_tag 'superuser' as superuser %}
            {% if superuser %}
                <li class="dropend">
                    <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                        Todo list
                        <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ todo_count }}</i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <strong class="dropdown-header">Todo list</strong>
                            {% access_tag 'develop' as develop %}
                            {% if develop %}
                                <a class="dropdown-item" href="{% url 'app_name_todo_list:create' %}">
                                    <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                                    todo create
                                </a>
                            {% endif %}
                            {% access_tag 'develop' as develop %}
                            {% if develop %}
                                <a class="dropdown-item" href="{% url 'app_name_todo_list:read_list' %}">
                                    <i class="fa-solid fa-list m-0 p-1"></i>
                                    todo list
                                    <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill"> {{ todo_count }}</i>
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</nav>

templates/app_todo_list/pages/todo_change.html
{% extends "app_todo_list/components/base.html" %}
{% load app_todo_list_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Todo change' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'app_todo_list/components/navbar.html' %}
{% endblock navbar %}

{% block header %}Todo change{% endblock header %}

{% block description %}this page contains form with todo data fields for send data to change todo{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom">
        <div class="d-flex text-start">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'app_name_todo_list:read_list' %}">
                <= all todos <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ todo_count }}</i>
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1 custom-background-transparent-middle m-0 p-0">
        <form action="{% url 'app_name_todo_list:update' todo.id %}"
                  method="POST"
                  target="_self"
                  enctype="multipart/form-data"
                  name="idea_create"
                  autocomplete="on"
                  class="text-center"
        >
            {% csrf_token %}
            <div>
                <div>
                    <label class="form-control-sm w-50 m-1">
                        Title:
                        <input type="text"
                               name="title"
                               required=""
                               placeholder="input 'title' here..."
                               value="{{ todo.title }}"
                               minlength="1"
                               maxlength="300"
                               class="form-control form-control-sm"
                        />
                        <small class="text-muted">chars count: <= 300</small>
                    </label>
                    <label class="form-control-sm w-75 m-1">
                        Description:
                        <textarea type="text"
                                  name="description"
                                  required=""
                                  placeholder="input 'description' here..."
                                  minlength="1"
                                  maxlength="3000"
                                  rows="3"
                                  class="form-control form-control-sm"
                        >{{ todo.description }}</textarea>
                        <small class="text-muted">chars count: <= 3000</small>
                    </label>
                </div>
            </div>
            <hr/>
            <div class="container-fluid text-center">
                <ul class="row row-cols-auto row-cols-md-auto row-cols-lg-auto nav justify-content-center">
                    <li class="m-1">
                        <button class="btn btn-sm btn-outline-primary" type="submit">submit</button>
                    </li>
                    <li class="m-1">
                        <button class="btn btn-sm btn-outline-warning" type="reset">reset</button>
                    </li>
                </ul>
            </div>
        </form>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'app_todo_list/components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

templates/app_todo_list/pages/todo_detail.html
{% extends "app_todo_list/components/base.html" %}
{% load app_todo_list_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Todo details' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'app_todo_list/components/navbar.html' %}
{% endblock navbar %}

{% block header %}Todo details{% endblock header %}

{% block description %}this page contains detail data from selected todo{% endblock description %}

{% block main %}
<div class="container shadow-lg m-0 p-0">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <a class="text-decoration-none lead btn btn-sm btn-outline-primary m-1 p-2" href="{% url 'app_name_todo_list:read_list' %}">
                <= all todos <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ todo_count }}</i>
            </a>
            <a class="text-decoration-none btn btn-sm btn-outline-success m-1 p-2" href="{% url 'app_name_todo_list:create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                create new todo
            </a>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-1 row-cols-lg-1">
        <div class="col">
            <div class="card custom-background-transparent-middle">
                <div class="card-header">
                    <div class="m-0 p-3">
                        <div class="d-flex justify-content-around">
                            <h5>{{todo.title}}</h5>
                            <form action="{% url 'app_name_todo_list:update' todo.id %}"
                                  method="POST"
                                  target="_self"
                                  enctype="multipart/form-data"
                                  name="idea_create"
                                  autocomplete="on"
                                  class="m-0 p-0"
                            >
                                {% csrf_token %}
                                <div>
                                    <input type="hidden"
                                       name="is_completed"
                                       required=""
                                       placeholder=""
                                       {% if todo.is_completed %}
                                            value="False"
                                       {% else %}
                                            value="True"
                                       {% endif %}
                                       minlength="1"
                                       maxlength="32"
                                       class="form-control form-control-lg"
                                />
                                </div>
                                <div class="btn-group m-0 p-1">
                                    {% if todo.is_completed %}
                                        <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                            <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                            not complete
                                        </button>
                                    {% else %}
                                        <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                            <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                            complete
                                        </button>
                                    {% endif %}
                                    <a href="{% url 'app_name_todo_list:update' todo.id %}" class="btn btn-sm btn-outline-warning m-0 p-1">
                                        <i class="fa-solid fa-screwdriver-wrench text-warning m-0 p-1"></i>
                                        change
                                    </a>
                                    <a href="{% url 'app_name_todo_list:delete' todo.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                        <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                        delete
                                    </a>
                                </div>
                            </form>
                        </div>
                        {% if todo.is_completed %}
                            <div class="feature-icon bg-success bg-gradient text-white">
                                <p class="m-0 p-1"></p>
                            </div>
                        {% else %}
                            <div class="feature-icon bg-danger bg-gradient text-white">
                                <p class="m-0 p-1"></p>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="card-body">
                    <p class="m-0 p-3">{{ todo.description }}</p>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between m-0 p-1">
                        <small class="text-warning">
                            {{ todo.created }} [created]
                        </small>
                        <small class="text-success">
                            {{ todo.updated }} [updated]
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock main %}

{% block footer %}
    {% include 'app_todo_list/components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}

templates/app_todo_list/pages/todo_list.html
{% extends "app_todo_list/components/base.html" %}
{% load app_todo_list_extras %}
{% load static %}


{% block head %}{% endblock head %}
{% block title %}
    {% text_upper_case text='Todo list' %}
{% endblock title %}

{% block prestyle %}{% endblock prestyle %}
{% block icon %}<link rel="icon" href="{% static 'img/logo512.png' %}" type="image/png">{% endblock icon %}
{% block poststyle %}{% endblock poststyle %}

{% block navbar %}
    {% include 'app_todo_list/components/navbar.html' %}
{% endblock navbar %}

{% block header %}Todo list{% endblock header %}

{% block description %}this page contains all todos{% endblock description %}

{% block main %}
<div class="container shadow-lg custom-background-transparent-hard m-0 p-0">
    <div class="shadow border-bottom m-0 p-0">
        <div class="d-flex justify-content-around">
            <h6 class="lead fw-bold m-1 p-2">todos <i class="btn btn-sm btn-dark bg-opacity-50 badge rounded-pill">{{ todo_count }}</i>:</h6>
            <a class="text-decoration-none btn btn-sm btn-outline-success m-1 p-2" href="{% url 'app_name_todo_list:create' %}">
                <i class="fa-solid fa-circle-plus m-0 p-1"></i>
                create new todo
            </a>
        </div>
    </div>
    <div class="text-end">
        <form action="{% url 'app_name_todo_list:read_list' %}"
        method="GET"
        target="_self"
        enctype="multipart/form-data"
        name="idea_create"
        autocomplete="on"
        class="m-0 p-0"
        >
        {% csrf_token %}
        <div>
        <input type="hidden"
           name="is_detail_view"
           required=""
           placeholder=""
           {% if is_detail_view %}
                value="False"
           {% else %}
                value="True"
           {% endif %}
           minlength="1"
           maxlength="32"
           class="form-control form-control-sm"
        />
        </div>
        {% if is_detail_view %}
            <button class="btn btn-lg m-0 p-1" type="submit">
                <i class="fa-solid fa-list-check text-secondary m-0 p-1"></i>
                list view
            </button>
        {% else %}
            <button class="btn btn-lg m-0 p-1" type="submit">
                <i class="fa-solid fa-calendar-week text-secondary m-0 p-"></i>
                detail view
            </button>
        {% endif %}
        </form>
    </div>

    {% if page %}
        <div class="container d-flex justify-content-center align-self-center">
            {% include 'app_todo_list/components/paginator.html' %}
        </div>

        {% if is_detail_view %}
            <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">
                {% for todo in page %}
                    <div class="col">
                        <div class="card border border-1 border-dark custom-background-transparent-middle m-1 p-0">
                            <div class="card-header">
                                <div class="m-0 p-3">
                                    <div class="d-flex justify-content-around">
                                        <a class="text-decoration-none text-dark" href="{% url 'app_name_todo_list:read' todo.id %}">
                                            <h5>{{ todo.title|cut_string:30 }}</h5>
                                        </a>
                                        <form action="{% url 'app_name_todo_list:update' todo.id %}"
                                              method="POST"
                                              target="_self"
                                              enctype="multipart/form-data"
                                              name="idea_create"
                                              autocomplete="on"
                                              class="m-0 p-0"
                                        >
                                            {% csrf_token %}
                                            <div>
                                                <input type="hidden"
                                                   name="is_completed"
                                                   required=""
                                                   placeholder=""
                                                   {% if todo.is_completed %}
                                                        value="False"
                                                   {% else %}
                                                        value="True"
                                                   {% endif %}
                                                   minlength="1"
                                                   maxlength="32"
                                                   class="form-control form-control-sm"
                                            />
                                            </div>
                                            <div class="btn-group m-0 p-1">
                                                {% if todo.is_completed %}
                                                    <button class="btn btn-sm btn-outline-danger m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-xmark text-danger m-0 p-1"></i>
                                                        not complete
                                                    </button>
                                                {% else %}
                                                    <button class="btn btn-sm btn-outline-success m-0 p-1" type="submit">
                                                        <i class="fa-solid fa-circle-check text-success m-0 p-1"></i>
                                                        complete
                                                    </button>
                                                {% endif %}
                                                <a href="{% url 'app_name_todo_list:delete' todo.id %}" class="btn btn-sm btn-outline-danger m-0 p-1">
                                                    <i class="fa-solid fa-circle-minus text-danger m-0 p-1"></i>
                                                    delete
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                    {% if todo.is_completed %}
                                        <div class="feature-icon bg-success bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% else %}
                                        <div class="feature-icon bg-danger bg-gradient text-white">
                                            <p class="m-0 p-1"></p>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="m-0 p-3">{{ todo.description|cut_string:100 }}</p>
                            </div>
                            <div class="card-footer">
                                <div class="d-flex justify-content-between m-0 p-1">
                                    <small class="text-warning m-1 p-0">
                                        {{ todo.created }} [created]
                                    </small>
                                    <small class="text-success m-1 p-0">
                                        {{ todo.updated }} [updated]
                                    </small>
                                </div>
                                <a class="text-decoration-none text-dark" href="{% url 'app_name_todo_list:read' todo.id %}">
                                    <button class="btn btn-sm btn-outline-primary w-100 m-0 p-1" type="submit">
                                        <i class="fa-solid fa-circle-info m-0 p-1"></i>
                                        details
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="m-0 p-1">
                <ul class="m-0">
                    {% for todo in page %}
                        <li class="text-start m-0 p-0 border border-1 border-dark p-1">
                            {% if todo.is_completed %}
                                <div class="feature-icon bg-success d-flex justify-content-between">
                            {% else %}
                                <div class="feature-icon bg-danger d-flex justify-content-between">
                            {% endif %}
                                <a class="text-decoration-none text-white small w-50" href="{% url 'app_name_todo_list:read' todo.id %}">
                                    <div class="d-flex">
                                        <h6 class="lead m-1 p-1">{{ todo.description|cut_string:20 }}</h6>
                                        <small class="m-0 p-2">{{ todo.description|cut_string:30 }}</small>
                                    </div>
                                </a>
                                <div class="m-1 p-1">
                                    <small class="text-white m-1 p-0">
                                        {{ todo.updated }} [updated]
                                    </small>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}

        <div class="container d-flex justify-content-center align-self-center">
            {% include 'app_todo_list/components/paginator.html' %}
        </div>
    {% else %}
        {% include 'app_todo_list/components/aborted.html' %}
    {% endif %}
</div>
{% endblock main %}

{% block footer %}
    {% include 'app_todo_list/components/footer.html' %}
{% endblock footer %}

{% block prescript %}{% endblock prescript %}
{% block postscript %}{% endblock postscript %}